version: '3.7'

services:
  nginx:
    image: registry.ops.katiecordescodes.com/personalsite-nginx
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
  phpfpm:
    image: registry.ops.katiecordescodes.com/personalsite-phpfpm
    build:
      context: .
      dockerfile: .docker/phpfpm/Dockerfile