version: "3.7"

services:
  personalsite:
    labels:
      - "traefik.http.middlewares.personalsite-redirect-websecure.redirectscheme.scheme=https"
      - "traefik.http.routers.personalsite.middlewares=personalsite-redirect-websecure"
      - "traefik.http.routers.personalsitesecure.rule=Host(`${PERSONALSITE_URL}`)"
      - "traefik.http.routers.personalsitesecure.entryPoints=websecure"
      - "traefik.http.routers.personalsitesecure.tls=true"
      - "traefik.http.routers.personalsitesecure.tls.certresolver=myresolver"