#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_test:
  path: /api/auth
  controller: App\Controller\TestController::getAuth

app_test2:
  path: /api/auth/profile
  controller: App\Controller\TestController::getAuthProfile